'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api} from '../../../lib/api';
import {getFieldToken} from '../../field/map/field-api';
import s from '../../../components/Workspace.module.css';
type Data={configured:boolean;status:string;expiresAt:number|null;page:{name:string;organisationId:string;verification:string}|null;drafts:{id:string;text:string;status:string}[]};
export default function LinkedInSettings(){
 const [data,setData]=useState<Data|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[text,setText]=useState('');
 const refresh=()=>api<Data>('/integrations/linkedin').then(setData);
 useEffect(()=>{void refresh().catch(e=>setMessage(e.message));const result=new URLSearchParams(location.search).get('connection');if(result)setMessage(result==='connected'?'LinkedIn connected. Publishing remains disabled.':'Connection failed or consent was declined. Start again.');},[]);
 async function action(path:string,body:unknown){if(busy)return;setBusy(true);setMessage('');try{await api('/integrations/linkedin'+path,body);await refresh();setMessage('Saved.');}catch(e){setMessage(e instanceof Error?e.message:'Request failed.');}finally{setBusy(false);}}
 return <main className={s.page}><section className={s.content}><Link href="/settings/roles">← Settings</Link><h1>Survey Guru Marketing · LinkedIn</h1><p>Workspace administrators only. Community Management access is awaiting vetting. Publishing is disabled.</p>{message&&<p role="status">{message}</p>}{data&&<>
 <article className={s.card}><h2>Connection: {data.status.replaceAll('_',' ')}</h2>{data.expiresAt&&<p>Token expires {new Date(data.expiresAt).toLocaleString()}. Reconnect when expired or revoked; no automatic token refresh is assumed.</p>}<p>Connecting stores an encrypted access token, expiry, granted scopes and workspace connection metadata. We do not collect profiles or feeds. Disconnect to delete active connection data, or contact consult@surveyguru.ai for deletion. Read the <Link href="/privacy">Privacy Policy</Link> before continuing.</p><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I consent to this use of my LinkedIn connection.</label><button disabled={busy||!consent||!data.configured} onClick={async()=>{setBusy(true);try{const token=await getFieldToken();const r=await fetch('/api/integrations/linkedin/start',{method:'POST',headers:{Authorization:'Bearer '+token}});const b=await r.json();if(!r.ok)throw new Error(b.message);location.assign(b.authorizationUrl);}catch(e){setMessage(e instanceof Error?e.message:'Connection failed.');setBusy(false);}}}>Connect / reconnect LinkedIn</button>{!data.configured&&<p>Configure credentials and only scopes already granted in the Developer Portal before connecting.</p>}<button disabled={busy} onClick={()=>void action('/disconnect',{})}>Disconnect and delete connection</button></article>
 <form className={s.card} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action('/page',Object.fromEntries(f));}}><h2>Page identity</h2><p>Administrator-entered metadata only; this does not verify Page access.</p>{data.page&&<p>{data.page.name} · {data.page.organisationId} · {data.page.verification}</p>}<label>Organisation ID<input name="organisationId" required pattern="[0-9]{1,30}"/></label><label>Page name<input name="name" required maxLength={150}/></label><button disabled={busy}>Save Page metadata</button></form>
 <form className={s.card} onSubmit={e=>{e.preventDefault();void action('/drafts',{text});}}><h2>Create a draft</h2><textarea required maxLength={3000} value={text} onChange={e=>setText(e.target.value)}/><button disabled={busy}>Save draft</button></form>
 {data.drafts.map(d=><article className={s.card} key={d.id}><h2>{d.status}</h2>{d.status==='DRAFT'?<><p>Preview the saved text before approval.</p><button disabled={busy} onClick={()=>void action('/drafts/'+d.id,{action:'preview'})}>Preview</button></>:<><p style={{whiteSpace:'pre-wrap'}}>{d.text}</p>{d.status==='PREVIEWED'&&<button disabled={busy} onClick={()=>void action('/drafts/'+d.id,{action:'approve'})}>Approve this text</button>}</>}<button disabled title="LinkedIn access and Page verification pending">Publish — awaiting access</button></article>)}
 </>}</section></main>;
}
