import Link from 'next/link';
import SurveyGuruSidebar from '../../../components/SurveyGuruSidebar';
import styles from './opportunity.module.css';

const stages=[['Finding','74 verified outlets now match the priority profile.'],['Evidence','Search coverage is reconciled across the core cluster; the western pocket remains incomplete.'],['Meaning','Outlet density and category potential are strengthening together rather than appearing as isolated discoveries.'],['Opportunity','Cluster 03 is becoming a credible growth pocket with enough evidence to justify focused validation.'],['Action','Finish the western search gap, validate the priority outlets, then assess the distribution response.']] as const;
const evidenceTrail=[
['Search geography','Core cluster searched','Verified','Project Map'],
['Outlet identity','74 priority-profile outlets','Verified','Outlet evidence'],
['Visit evidence','Identity + location reconciled','Verified','QA record'],
['Western pocket','18.6 km remains incomplete','Unknown','Field Live Map'],
] as const;

export default function OpportunityDemoPage(){return <main className={styles.page}><div className={styles.shell}>
<SurveyGuruSidebar active="opportunities" />
<section className={styles.main}><div className={styles.workspace}>
<header className={styles.header}><div><p className={styles.eyebrow}>Survey Guru · Story + Explore · Opportunity 03</p><h1>From field evidence<br/>to a growth case.</h1><p>Story creates understanding. Explore creates conviction.</p></div><Link className={styles.back} href="/dashboard">← Dashboard</Link></header>
<section className={styles.hero}><div><span className={styles.badge}>HIGH OPPORTUNITY · VALIDATION ACTIVE</span><h2>Dobsonville growth cluster</h2><p>The market picture is moving from discovery to a defensible opportunity. The evidence is strong enough to focus attention—but not yet complete enough to skip the remaining search.</p></div><div className={styles.heroMetric}><strong>74</strong><span>verified priority-profile outlets</span><small>312 across all current clusters</small></div></section>
<section className={styles.story}>{stages.map(([stage,copy],i)=><article key={stage}><span>{String(i+1).padStart(2,'0')}</span><div><p className={styles.eyebrow}>{stage}</p><h3>{copy}</h3></div></article>)}</section>
<section className={styles.explore} id="explore"><div className={styles.exploreHead}><div><p className={styles.eyebrow}>Explore the evidence</p><h2>Trace every claim back to field reality.</h2></div><span>72% searched</span></div><div className={styles.exploreGrid}><div className={styles.map}><div className={styles.grid}/><div className={`${styles.road} ${styles.r1}`}/><div className={`${styles.road} ${styles.r2}`}/><div className={`${styles.road} ${styles.r3}`}/><div className={styles.covered}/><div className={styles.partial}/><div className={`${styles.pulse} ${styles.p1}`}><b>74</b><small>verified outlets</small></div><div className={`${styles.pulse} ${styles.p2}`}><b>03</b><small>cluster</small></div><div className={styles.gap}>Western pocket · unknown until searched</div></div><aside className={styles.lens}><p className={styles.eyebrow}>Decision lens</p><h3>What can the evidence support?</h3><div><span>Verified opportunity</span><strong>74 outlets</strong></div><div><span>Search confidence</span><strong>72%</strong></div><div><span>Validation state</span><strong>Focused next</strong></div><div><span>Network decision</span><strong>Not yet</strong></div><p>Opportunity is a reason to focus field work—not permission to infer what has not been searched.</p><Link href="/projects/demo/map">Inspect coverage evidence →</Link></aside></div><div className={styles.signals}><div><strong>↑ Outlet density</strong><span>Verified outlets are concentrating inside searched geography.</span></div><div><strong>↑ Category potential</strong><span>Observed opportunity is strengthening across reconciled visits.</span></div><div><strong>✓ Evidence reconciled</strong><span>Known search evidence is separated from unknown geography.</span></div></div></section>
<section className={styles.explore} aria-label="Opportunity evidence trail"><div className={styles.exploreHead}><div><p className={styles.eyebrow}>Evidence trail</p><h2>Why Survey Guru believes this opportunity exists.</h2></div><span>Auditable</span></div><div className={styles.signals}>{evidenceTrail.map(([source,finding,state,origin])=><div key={source}><strong>{source} · {state}</strong><span>{finding} · Source: {origin}</span></div>)}</div><p>Verified evidence supports the current growth case. Unknown geography remains explicitly outside the claim until field search and QA are complete.</p></section>
<section className={styles.decision}><div><p className={styles.eyebrow}>Recommended next move</p><h2>Complete the evidence before changing the network.</h2><p>Finish the remaining search, validate the 74 priority outlets and preserve the evidence trail. Once confirmed, this opportunity becomes ready for distribution-response analysis.</p></div><div className={styles.actions}><Link href="/field/map">Finish field validation →</Link><Link href="/projects/demo/map">Explore coverage</Link></div></section>
<footer className={styles.footer}><strong>Capture truth → Reveal opportunity → Tell the story.</strong><span>Task Expert Systems</span></footer>
</div></section></div></main>}
