'use client';
import { useState } from 'react';
import s from '../app/public.module.css';
const stores = [
  {name:'Corner Market',type:'Spaza shop',fridge:'Yes · 2 display fridges',hours:'Mon–Sat 07:00–20:00 · Sun 08:00–17:00',x:28,y:32,category:'Everyday groceries',status:'Verified'},
  {name:'Sunrise Fresh Foods',type:'Mini supermarket',fridge:'Yes · 4 display fridges',hours:'Daily 08:00–19:00',x:63,y:28,category:'Fresh produce and groceries',status:'Verified'},
  {name:'Mango Street Café',type:'Takeaway and café',fridge:'Yes · 1 drinks fridge',hours:'Mon–Sat 09:00–21:00 · Sun closed',x:46,y:58,category:'Prepared food and drinks',status:'Awaiting QA'},
  {name:'Westside Essentials',type:'General dealer',fridge:'No',hours:'Mon–Fri 08:00–18:00 · Sat–Sun 09:00–15:00',x:72,y:69,category:'Household essentials',status:'Verified'},
];
export default function DemoStoreMap(){const [selected,setSelected]=useState(0);const store=stores[selected]!;
return <section className={s.demoExplorer} aria-label="Illustrative project and stores"><div className={s.demoMap}><div className={s.mapHeading}><span className={s.eyebrow}>DEMO PROJECT AREA</span><strong>Westside retail survey</strong><small>Illustrated map · Select a numbered store</small></div><svg viewBox="0 0 600 460" preserveAspectRatio="none" aria-hidden="true"><rect width="600" height="460" fill="#e7eee5"/><path d="M0 350Q150 250 180 460H0ZM430 0H600V170Q440 130 430 0" fill="#c6dfbc"/><path d="M-20 190Q180 140 290 240T630 260" stroke="#bbdce6" strokeWidth="32" fill="none"/><g stroke="#fff" strokeWidth="18"><path d="M0 115H600M0 220H600M0 335H600M125 0V460M280 0V460M435 0V460"/></g><path d="M90 95L460 70L535 330L365 405L80 340Z" fill="#06a881" fillOpacity=".09" stroke="#087c65" strokeWidth="3" strokeDasharray="9 6"/><path d="M125 115H435V335H280V220H125" fill="none" stroke="#05ae87" strokeWidth="7" strokeLinecap="round"/><path d="M280 335H125" stroke="#eaa62b" strokeWidth="7"/><g fill="#5b7269" fontSize="12" fontFamily="sans-serif"><text x="295" y="210">MANGO STREET</text><text x="140" y="325">MARKET ROAD</text><text x="460" y="420">WESTSIDE PARK</text></g></svg>{stores.map((item,i)=><button key={item.name} className={`${s.storePin} ${i===selected?s.activePin:''}`} style={{left:`${item.x}%`,top:`${item.y}%`}} aria-label={`View ${item.name}`} aria-pressed={i===selected} onClick={()=>setSelected(i)}>{i+1}</button>)}<div className={s.mapLegend}><span>● Confirmed route</span><span>🟠 Needs review</span><span>┄ Project boundary</span></div></div><aside className={s.storeDetails} aria-live="polite"><span className={s.eyebrow}>STORE {selected+1} / {stores.length} · DEMO DATA</span><h2>{store.name}</h2><span className={s.storeStatus}>{store.status}</span><dl><div><dt>Store type</dt><dd>{store.type}</dd></div><div><dt>Fridge available</dt><dd>{store.fridge}</dd></div><div><dt>Operating hours</dt><dd>{store.hours}</dd></div><div><dt>Products</dt><dd>{store.category}</dd></div></dl><p>Every outlet tells part of the area’s story. Select another marker to explore its evidence.</p></aside></section>;}
