'use client';
import { useState } from 'react';
import s from '../app/public.module.css';
export default function DemoWalkthrough(){
 const [step,setStep]=useState(0);const [decision,setDecision]=useState<'pending'|'accepted'|'returned'>('pending');const [message,setMessage]=useState('');
 const accepted=decision==='accepted';
 const titles=['Give every observation a place.','Check the record before counting it.','See the effect of reviewed evidence.'];
 const copy=['An agent records Corner Market inside the Westside project area. Store details and location evidence travel with the record into review.','The reviewer checks the trading name, location and capture details. Accept the sample or ask the capturer for a correction.',`${accepted?'Corner Market now contributes to the accepted outlet total.':'Corner Market does not yet contribute to the accepted outlet total.'} Street coverage remains separate: accepting a store does not prove that every road was searched.`];
 return <section style={{marginTop:48}} aria-label="Capture to insight walkthrough"><p className={s.eyebrow}>SEE HOW THE EVIDENCE MOVES</p><h2>One store. Three steps. A clearer decision.</h2><p>This walkthrough follows Corner Market. Accept it in QA to see the area total change, or return it for correction.</p><div className={s.actions} role="group" aria-label="Walkthrough stages">{['Capture','Review','Understand'].map((label,i)=><button key={label} type="button" className={step===i?s.button:s.secondary} aria-pressed={step===i} onClick={()=>{setStep(i);setMessage('');}}>{`0${i+1} · ${label}`}</button>)}</div><div className={s.walkthrough}><div><p className={s.eyebrow}>{['FIELD CAPTURE','QUALITY REVIEW','AREA INSIGHT'][step]}</p><h2>{titles[step]}</h2><p>{copy[step]}</p><div className={s.actions}>{step===0?<button className={s.button} onClick={()=>{setDecision('pending');setStep(1);setMessage('Sample sent to review.');}}>Send sample to review →</button>:step===1?<><button className={s.button} onClick={()=>{setDecision('accepted');setStep(2);setMessage('Sample accepted. The area total has increased by one.');}}>Accept sample →</button><button className={s.secondary} onClick={()=>{setDecision('returned');setMessage('Sample returned: please confirm the trading name. The capturer receives the reason; the accepted total does not increase.');}}>Request correction</button></>:<button className={s.secondary} onClick={()=>{setDecision('pending');setStep(0);setMessage('Walkthrough reset.');}}>Restart the walkthrough</button>}</div><p role="status">{message}</p></div><div className={s.card} style={{background:'var(--sg-surface-info)'}}><p className={s.eyebrow}>{step===2?'WESTSIDE · SAMPLE AREA SUMMARY':'CORNER MARKET · SAMPLE RECORD'}</p>{step===2?<><span>Accepted outlets</span><strong className={s.metric}>{accepted?25:24}</strong><p>{accepted?'+1 from this review':'Sample store not yet accepted'}</p><p>Awaiting QA: <b>{decision==='pending'?4:3}</b></p>{decision==='returned'&&<p>Awaiting capturer correction: <b>1</b></p>}<p>Search coverage: <b>Not assessed in this demo</b></p></>:<><h3>Corner Market</h3><p>Store type: <b>Spaza shop</b></p><p>Refrigeration: <b>2 display fridges</b></p><p>Operating hours: <b>07:00–20:00</b></p><p>Assigned area: <b>Westside</b></p><p>Status: <b>{accepted?'Accepted':decision==='returned'?'Returned for correction':'Awaiting review'}</b></p></>}<small>Illustrative evidence only. A real review checks protected photo and location evidence.</small></div></div></section>;
}
