'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import SurveyGuruSidebar from './SurveyGuruSidebar';
import ProjectGoogleMap from '../app/projects/demo/map/ProjectGoogleMap';
import mapStyles from '../app/projects/demo/map/project-map.module.css';
import QaReviewQueue from '../app/qa/QaReviewQueue';
import { api } from '../lib/api';
import s from './Workspace.module.css';
export default function ProjectWorkspace({ qa = false }: { qa?: boolean }) {
  const [projects,setProjects] = useState<{id:string;name:string}[]>([]); const [project,setProject] = useState(''); const [message,setMessage] = useState('Loading authorised projects…');
  useEffect(() => { const abort = new AbortController(); void api<{projects:{id:string;name:string}[]}>('/projects/active',undefined,abort.signal).then(r => { if(abort.signal.aborted)return;setProjects(r.projects);const wanted=new URLSearchParams(window.location.search).get('project');setProject(r.projects.find(p=>p.id===wanted)?.id??r.projects[0]?.id??'');setMessage(r.projects.length?'':'No projects available.'); }).catch(e=>{if(!abort.signal.aborted)setMessage(e.message);});return()=>abort.abort(); },[]);
  return <main className={s.page}><div className={s.shell}><SurveyGuruSidebar active={qa?'qa':'project-map'}/><section className={s.content}><header className={s.header}><div><p className={s.eyebrow}>{qa?'Evidence and quality assurance':'Project intelligence'}</p><h1>{qa?'Submitted customers and QA':'Project map and coverage'}</h1></div><Link href="/operations">Project areas →</Link></header><label>Active project<select value={project} onChange={e=>setProject(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{message&&<p className={s.status} role="status">{message}</p>}{project&&(qa?<QaReviewQueue key={project} projectId={project}/>:<><div className={s.card} style={{marginTop:24}}><ProjectGoogleMap projectId={project} onProjectChange={setProject} classes={{mapToolbar:mapStyles.mapToolbar,mapTypes:mapStyles.mapTypes,projectChooser:mapStyles.projectChooser,baseMapTypes:mapStyles.baseMapTypes,selected:mapStyles.selected,mapTools:mapStyles.mapTools}}/></div><div className={s.grid}><article className={s.card}><h2>Coverage evidence model</h2>{[['Confirmed','Movement is matched to a project street.'],['Unresolved','More continuous or accurate evidence is required.'],['Not walked','No sufficient movement evidence has been confirmed.']].map(([label,copy])=><div className={s.row} key={label}><strong>{label}</strong><span>{copy}</span></div>)}</article><article className={s.card}><h2>Explore the selected project</h2><p>Inspect submitted customer status, observed brand presence and field activity.</p><Link href={`/insights?project=${encodeURIComponent(project)}`}>Open project insights →</Link><p><Link href={`/qa?project=${encodeURIComponent(project)}`}>Open customer evidence and QA →</Link></p></article></div></>)}</section></div></main>;
}
