import s from './Workspace.module.css';
export type StoreInsightData={acceptedStores:number;storesWithProducts:number;productRows:number;pricedRows:number;volumeRows:number;recentSubmissions:number;previousSubmissions:number;trend:{day:string;submitted:number;accepted:number}[];products:{brand:string;product:string;stores:number;purchaseMean:number|null;sellingMean:number|null;sellingMin:number|null;sellingMax:number|null;priceSamples:number;meanUnitSpread:number|null;spreadSamples:number;reportedUnits:number|null;volumeSamples:number}[]};
const money=(n:number|null)=>n===null?'Not captured':n.toLocaleString('en-ZA',{style:'currency',currency:'ZAR'});
export default function StoreInsightSummary({data}:{data:StoreInsightData}){
 const maximum=Math.max(1,...data.trend.map(d=>d.submitted));
 return <section className={s.card}><p className={s.eyebrow}>Store data and key findings</p><h2>What the captured evidence tells us</h2><div className={s.metrics}><article><strong className={s.metric}>{data.storesWithProducts}/{data.acceptedStores}</strong><p>Accepted stores with product records</p></article><article><strong className={s.metric}>{data.pricedRows}/{data.productRows}</strong><p>Product rows with both prices</p></article><article><strong className={s.metric}>{data.volumeRows}/{data.productRows}</strong><p>Product rows with reported volumes</p></article></div>
 {data.products[0]&&<p><strong>Widest observed product presence:</strong> {data.products[0].brand} · {data.products[0].product}, recorded at {data.products[0].stores} accepted stores.</p>}
 {data.pricedRows<data.productRows&&<p><strong>Follow-up:</strong> {data.productRows-data.pricedRows} product rows lack a purchase or selling price. Complete these before comparing price differences.</p>}
 <h3>Product and pack comparisons</h3><p>All currently accepted captures in the selected area. Prices are ZAR per captured unit. Different product or pack descriptions remain separate. Reported daily volumes are not audited transactions.</p>
 {data.products.length?<div style={{overflowX:'auto'}}><table><thead><tr>{['Brand / product','Stores','Mean purchase','Mean selling / range','Mean unit difference','Reported units/day'].map(x=><th key={x} style={{padding:10,textAlign:'left'}}>{x}</th>)}</tr></thead><tbody>{data.products.map((p,i)=><tr key={i}><td style={{padding:10}}>{p.brand} · {p.product}</td><td style={{padding:10}}>{p.stores}</td><td style={{padding:10}}>{money(p.purchaseMean)}</td><td style={{padding:10}}>{money(p.sellingMean)}<br/><small>{money(p.sellingMin)} – {money(p.sellingMax)} · {p.priceSamples} rows</small></td><td style={{padding:10}}>{money(p.meanUnitSpread)}<br/><small>{p.spreadSamples} paired rows</small></td><td style={{padding:10}}>{p.reportedUnits??'Not captured'}<br/><small>{p.volumeSamples} reporting rows</small></td></tr>)}</tbody></table></div>:<p>No accepted product evidence yet.</p>}
 <p>Unit difference = selling price minus purchase price for paired records; it excludes operating costs and is not net profit. Missing values are excluded from averages. Repeat visits may count separately.</p>
 <h3>Capture activity · last 14 days</h3><p>{data.recentSubmissions} submissions in the latest 7 days versus {data.previousSubmissions} in the preceding 7 days. This measures capture activity, not a sales or market-demand trend. Resubmissions use their latest submission date.</p>
 <div aria-label="Daily submissions">{data.trend.map(d=><div key={d.day} style={{display:'grid',gridTemplateColumns:'100px 1fr 55px',gap:10,alignItems:'center',margin:'7px 0'}}><time>{d.day}</time><span style={{background:'rgba(0,160,130,.15)',borderRadius:4}}><span style={{display:'block',height:12,width:(d.submitted/maximum*100)+'%',background:'#00b991',borderRadius:4}}/></span><span>{d.submitted}</span></div>)}</div>
 </section>;
}
