import type {Metadata} from 'next';
import Link from 'next/link';
import PublicNav from '../../components/PublicNav';
import s from '../public.module.css';
export const metadata:Metadata={title:'Privacy Policy | Survey Guru',alternates:{canonical:'https://surveyguru.ai/privacy'}};
export default function PrivacyPage(){return <main className={s.page}><div className={s.wrap}><PublicNav/><article className={s.card} style={{lineHeight:1.8}}>
 <p className={s.eyebrow}>Your information and your choices</p><h1>Privacy Policy</h1><p>Last updated: 19 September 2026</p>
 <h2>Who we are</h2><p>Survey Guru is operated by Task Expert Systems (Pty) Ltd (“TES”, “we”, “us”). This policy covers surveyguru.ai, the Survey Guru application and the Survey Guru Marketing LinkedIn integration. Contact <a href="mailto:consult@surveyguru.ai">consult@surveyguru.ai</a> for privacy questions or requests. Where we process field-survey information on a customer’s instructions, that customer determines the survey purposes and TES acts as its service provider. We are responsible for our own website enquiries, account administration and marketing integration.</p>
 <h2>Information we process</h2><ul><li>Consultation enquiries: your name, work email, company, project description, submission time and request reference.</li><li>Account and service records: sign-in identifiers, contact details, workspace membership, roles, assignments and review actions.</li><li>Field evidence: store and business details, product information, photographs, locations and movement evidence collected during an authorised survey. Device permission is required for location and camera access. Field users should avoid collecting unnecessary personal information or photographs of people.</li><li>Technical information: service requests, errors and security records; essential sign-in, appearance and offline-storage data needed to operate the application.</li></ul>
 <h2>Why we use it</h2><p>We use information to respond to enquiries, provide contracted survey services, manage accounts, validate field evidence, protect the service and support authorised reporting. Depending on the context and applicable law, processing relies on your consent, steps requested before a contract, performance of a contract, legal obligations or legitimate operational and security interests. Providing consultation details is voluntary, but the required fields are necessary to respond meaningfully.</p>
 <h2>LinkedIn connection and marketing</h2><p>Only an authorised workspace administrator can initiate a connection. When you consent on LinkedIn, we receive an access token, its expiry and available scope information. We store an encrypted token, the Survey Guru administrator and workspace identifiers, connection times and Page identity entered by an administrator. The initial integration does not retrieve member profiles, contacts, messages, followers or feeds. Page identity is unverified until the necessary LinkedIn permissions and verification are available.</p><p>We use connection information solely to provide the LinkedIn functionality you authorise. We do not sell LinkedIn data, use it for advertising audiences, feed it to AI training systems or share it as a data product. The initial publishing workflow requires Draft → Preview → Approve → Publish; external publishing is currently disabled while access and Page permissions are pending. There is no autonomous posting or background profile collection.</p><p>You can disconnect in LinkedIn settings within Survey Guru. This deletes the stored connection credentials and Page metadata from our active database. You can also revoke the application in LinkedIn’s permitted-services settings. Email us to request deletion of information associated with your connection, particularly if you no longer have workspace access. We delete LinkedIn-derived data on a verified deletion request or account closure, except where retention is legally required. User-authored drafts are separate from LinkedIn-derived information; request their deletion if needed.</p>
 <h2>Who receives information</h2><p>Authorised customer team members receive information within their assigned roles and workspace. Our service providers include Netlify for hosting, Google Cloud/Firebase for authentication, storage and API services, and Microsoft 365 for consultation email. LinkedIn receives OAuth requests and the information necessary to process your consent, under its own <a href="https://www.linkedin.com/legal/privacy-policy">Privacy Policy</a>. We may disclose information when legally required or necessary to protect rights and security. We do not sell personal information.</p>
 <h2>Storage, security and international processing</h2><p>We use access controls, encrypted network connections and restricted server-side credentials. LinkedIn access tokens are additionally encrypted before database storage and are never returned to browser code. Hosting and service providers may process information outside your country, including outside South Africa. We use contractual and technical safeguards appropriate to the processing and applicable data-protection requirements. No internet service can guarantee absolute security.</p>
 <h2>Retention</h2><p>Enquiries are retained while we address the enquiry and any resulting business relationship, subject to legal recordkeeping needs. Field and account records follow the customer’s service arrangements and applicable obligations. We retain LinkedIn connection information while the connection is maintained; expired tokens cannot be used and reconnection requires new consent. Disconnect or a verified deletion request removes active connection data. Backups and security records may remain for their normal retention cycle, with access restricted and not used to resume a disconnected integration.</p>
 <h2>Cookies and device storage</h2><p>Survey Guru uses essential authentication and security mechanisms, including a short-lived, HttpOnly OAuth cookie to prevent forged LinkedIn connections. It expires after ten minutes or is cleared when the callback completes. Browser storage supports appearance preferences and offline field work. Clearing browser storage can remove unsynchronised field evidence; synchronise it first. This integration does not add advertising cookies.</p>
 <h2>Your rights and complaints</h2><p>Subject to applicable law, including South Africa’s POPIA where applicable, you may request access, correction or deletion, object to processing, or withdraw consent. Withdrawal does not affect prior lawful processing. Contact <a href="mailto:consult@surveyguru.ai">consult@surveyguru.ai</a> with “Privacy request” in the subject and enough context to locate the relevant records; do not send passwords or tokens. We may verify your identity and refer customer-controlled survey requests to the responsible customer. You may also complain to the <a href="https://inforegulator.org.za/">Information Regulator of South Africa</a> or your applicable supervisory authority.</p>
 <h2>Children and policy changes</h2><p>The service is intended for business users, not children. Contact us if you believe a child’s information was submitted inappropriately. We will publish changes here with a revised date and communicate material changes to affected users where required. A new purpose or permission requiring consent will not be enabled merely by changing this page.</p>
 <footer className={s.footer}><Link href="/">Survey Guru home</Link><a href="mailto:consult@surveyguru.ai">Contact TES</a></footer>
 </article></div></main>;}
