import {test} from 'node:test';
import assert from 'node:assert/strict';
import Fastify from 'fastify';
import {registerBusinessRoutes, businessPermissions} from '../src/business-routes.js';
import {AuthorisationError} from '../src/authority.js';
function setup(platform=false){
 const docs=new Map<string,any>([['workspaces/client',{kind:'business',status:'active',name:'Client'}],['projects/p',{workspaceId:'client',status:'active'}],['projects/tes',{workspaceId:'tes',status:'active'}]]);let seq=0;
 const snap=(path:string):any=>({id:path.split('/')[1],exists:docs.has(path),get:(k:string)=>docs.get(path)?.[k],data:()=>docs.get(path),ref:ref(path)});
 const ref=(path:string):any=>({path,get:async()=>snap(path),create:async(v:any)=>docs.set(path,v),id:path.split('/')[1]});
 const query=(name:string,filters:any[]=[]):any=>({doc:(id:string)=>ref(name+'/'+(id??`new${seq++}`)),where:(k:string,_op:string,v:any)=>query(name,[...filters,[k,v]]),get:async()=>({docs:[...docs.keys()].filter(p=>p.startsWith(name+'/')&&filters.every(([k,v])=>docs.get(p)[k]===v)).map(snap)})});
 const firestore={collection:query,runTransaction:async(fn:any)=>{const writes:any[]=[];await fn({get:async(r:any)=>r.get(),set:(r:any,v:any,o:any)=>writes.push(()=>docs.set(r.path,o?.merge?{...docs.get(r.path),...v}:v)),create:(r:any,v:any)=>writes.push(()=>docs.set(r.path,v))});writes.forEach(f=>f());}};
 const authority={workspaceId:'client',permissions:new Set(platform?['platform.admin']:['business.admin'])};const identity={uid:'manager'};
 const app=Fastify();app.setErrorHandler((e,_,r)=>r.code(e instanceof AuthorisationError?403:400).send({message:e.message}));registerBusinessRoutes(app,async()=>({identity,authority,firestore,auth:{getUserByEmail:async()=>({uid:'employee',email:'employee@example.com'})}} as never));
 return {app,docs,authority};
}
const payload={email:'employee@example.com',role:'viewer',capture:false,active:true,projectIds:['p']};
test('business employee receives only report permissions and selected projects',async()=>{const {app,docs}=setup();const r=await app.inject({method:'POST',url:'/api/v1/businesses/client/people',payload});assert.equal(r.statusCode,200,r.body);assert.equal(docs.get('workspaceMemberships/wsm_employee').workspaceId,'client');assert.deepEqual(docs.get('roleDefinitions/client_business_viewer_read').permissions,['project.read','coverage.read','report.read']);assert.equal(docs.get('projectMemberships/prjm_p_employee').status,'active');await app.close();});
test('business admins cannot create businesses, appoint admins or access another business',async()=>{const {app}=setup();for(const [url,p] of [['/api/v1/businesses',{name:'Other'}],['/api/v1/businesses/other/people',payload],['/api/v1/businesses/client/people',{...payload,role:'admin'}]] as const){assert.equal((await app.inject({method:'POST',url,payload:p})).statusCode,403);}assert.equal((await app.inject('/api/v1/businesses/other')).statusCode,403);await app.close();});
test('cross-business project grants and employee transfers are denied without writes',async()=>{const {app,docs}=setup();assert.equal((await app.inject({method:'POST',url:'/api/v1/businesses/client/people',payload:{...payload,projectIds:['tes']}})).statusCode,403);assert.ok(!docs.has('users/employee'));docs.set('workspaceMemberships/other',{workspaceId:'tes',userId:'employee',status:'active'});assert.equal((await app.inject({method:'POST',url:'/api/v1/businesses/client/people',payload})).statusCode,403);assert.ok(!docs.has('users/employee'));await app.close();});
test('TES can appoint a scoped business admin with optional capture',async()=>{const {app,docs}=setup(true);const r=await app.inject({method:'POST',url:'/api/v1/businesses/client/people',payload:{...payload,role:'admin',capture:true}});assert.equal(r.statusCode,200,r.body);const permissions=docs.get('roleDefinitions/client_business_admin_capture').permissions;assert.ok(permissions.includes('business.admin'));assert.ok(permissions.includes('field.capture'));assert.ok(!permissions.includes('workspace.admin'));assert.ok(!permissions.includes('platform.admin'));await app.close();});
test('deactivation removes membership and project access; business admin cannot modify another admin',async()=>{const {app,docs}=setup();await app.inject({method:'POST',url:'/api/v1/businesses/client/people',payload});await app.inject({method:'POST',url:'/api/v1/businesses/client/people',payload:{...payload,active:false}});assert.equal(docs.get('workspaceMemberships/wsm_employee').status,'inactive');assert.equal(docs.get('projectMemberships/prjm_p_employee').status,'inactive');docs.set('roleDefinitions/admin',{permissions:['business.admin']});docs.get('workspaceMemberships/wsm_employee').roleKey='admin';docs.get('workspaceMemberships/wsm_employee').roleKeys=['client_business_viewer_read','admin'];assert.equal((await app.inject({method:'POST',url:'/api/v1/businesses/client/people',payload})).statusCode,403);await app.close();});
test('unsupported roles and nonboolean capture fail validation',()=>{assert.throws(()=>businessPermissions('platform.admin',false));assert.throws(()=>businessPermissions('viewer','true'));});
