import test from 'node:test';
import assert from 'node:assert/strict';
import {createDecipheriv} from 'node:crypto';
import Fastify from 'fastify';
import {registerLinkedInRoutes} from '../src/linkedin-routes.js';
import {LinkedInError,linkedinConfig,tokenExpiry,connectionState,encryptToken,hash,workflow} from '../src/linkedin.js';
import {AuthorisationError} from '../src/authority.js';
function configure(){process.env.LINKEDIN_ENV='production';process.env.LINKEDIN_PROD_CLIENT_ID='test-client';process.env.LINKEDIN_PROD_CLIENT_SECRET='test-secret';process.env.LINKEDIN_PROD_TOKEN_KEY='ab'.repeat(32);process.env.LINKEDIN_PROD_REDIRECT_URI='https://surveyguru.ai/api/integrations/linkedin/callback';process.env.LINKEDIN_PROD_SCOPES='test_granted_scope';}
function setup(admin=true){
 configure();const docs=new Map<string,any>();let next=0;
 const ref=(path:string):any=>({path,id:path.split('/').at(-1),get:async()=>snap(path),set:async(v:any)=>docs.set(path,v),delete:async()=>docs.delete(path)});
 const snap=(path:string):any=>({id:path.split('/').at(-1),exists:docs.has(path),get:(k:string)=>docs.get(path)?.[k],data:()=>docs.get(path)});
 const collection=(name:string,filters:[string,unknown][]=[]):any=>({doc:(key:string)=>ref(name+'/'+key),where:(k:string,_op:string,v:unknown)=>collection(name,[...filters,[k,v]]),limit:()=>collection(name,filters),get:async()=>({docs:[...docs.keys()].filter(k=>k.startsWith(name+'/')&&filters.every(([f,v])=>docs.get(k)?.[f]===v)).map(snap)}),add:async(v:any)=>{const r=ref(name+'/'+(++next));await r.set(v);return r;}});
 const firestore:any={collection,runTransaction:async(fn:any)=>{const writes:(()=>void)[]=[];const result=await fn({get:async(r:any)=>snap(r.path),set:(r:any,v:any)=>writes.push(()=>docs.set(r.path,v)),update:(r:any,v:any)=>writes.push(()=>docs.set(r.path,{...docs.get(r.path),...v})),delete:(r:any)=>writes.push(()=>docs.delete(r.path))});writes.forEach(f=>f());return result;},batch:()=>{const paths:string[]=[];return {delete:(r:any)=>paths.push(r.path),commit:async()=>paths.forEach(p=>docs.delete(p))};}};
 const identity={uid:'admin'};const authority={identity,workspaceId:'workspace',membershipId:'m',roleKey:'admin',permissions:new Set(admin?['workspace.admin']:['field.capture']),projectIds:new Set<string>(),assignmentIds:new Set<string>()};
 const app=Fastify();app.setErrorHandler((e,_,r)=>r.code(e instanceof LinkedInError?e.statusCode:e instanceof AuthorisationError?403:500).send({message:e.message}));
 registerLinkedInRoutes(app,async()=>({identity,authority,firestore} as never),()=>({firestore} as never),async()=>authority as never);
 return {app,docs,authority};
}
const base='/api/v1/integrations/linkedin';const binding='cd'.repeat(32);
test('configuration fails closed without granted scopes and isolates environments',()=>{configure();assert.equal(linkedinConfig().environment,'production');delete process.env.LINKEDIN_PROD_SCOPES;assert.throws(linkedinConfig);configure();process.env.LINKEDIN_ENV='development';assert.throws(linkedinConfig);configure();process.env.LINKEDIN_PROD_REDIRECT_URI='https://evil.test/api/integrations/linkedin/callback';assert.throws(linkedinConfig);configure();});
test('token TTL uses provider value; expiry and seven-day warning are explicit',()=>{assert.equal(tokenExpiry(5184000,0),5184000000);assert.equal(tokenExpiry(60,0),60000);assert.throws(()=>tokenExpiry('5184000'));assert.equal(connectionState(100,100),'RECONNECT_REQUIRED');assert.equal(connectionState(200,100),'EXPIRING_SOON');assert.equal(connectionState(700000000,0),'CONNECTED');});
test('AES GCM binds ciphertext to workspace and detects tampering',()=>{const key='ab'.repeat(32);const stored=encryptToken('private-access-token',key,'workspace');assert.ok(!JSON.stringify(stored).includes('private-access-token'));const d=createDecipheriv('aes-256-gcm',Buffer.from(key,'hex'),Buffer.from(stored.iv,'hex'));d.setAAD(Buffer.from('workspace'));d.setAuthTag(Buffer.from(stored.tag,'hex'));assert.equal(Buffer.concat([d.update(Buffer.from(stored.ciphertext,'base64')),d.final()]).toString(),'private-access-token');const wrong=createDecipheriv('aes-256-gcm',Buffer.from(key,'hex'),Buffer.from(stored.iv,'hex'));wrong.setAAD(Buffer.from('other'));wrong.setAuthTag(Buffer.from(stored.tag,'hex'));wrong.update(Buffer.from(stored.ciphertext,'base64'));assert.throws(()=>wrong.final());});
test('field role cannot access integration endpoints',async()=>{const {app}=setup(false);for(const [method,url,payload] of [['GET',base,undefined],['POST',base+'/start',{binding}],['POST',base+'/disconnect',{}],['POST',base+'/drafts',{text:'hello'}]] as const){assert.equal((await app.inject({method,url,...payload?{payload}:{}})).statusCode,403);}await app.close();});
test('OAuth rejects wrong browser, expires state, exchanges once and never returns token',async()=>{
 const {app,docs}=setup();const old=fetch;let calls=0;globalThis.fetch=async()=>{calls++;return Response.json({access_token:'private-access-token',expires_in:5184000,scope:'test_granted_scope'});};
 try{const start=await app.inject({method:'POST',url:base+'/start',payload:{binding}});assert.equal(start.statusCode,200);const state=new URL(start.json().authorizationUrl).searchParams.get('state')!;const path='linkedinOAuthStates/'+state.split('.')[0];assert.ok(!JSON.stringify(docs.get(path)).includes(binding));
 const callback=(b:string)=>app.inject({method:'POST',url:base+'/callback',payload:{state,binding:b,code:'secret-code'}});
 assert.equal((await callback('ef'.repeat(32))).statusCode,400);assert.equal(calls,0);docs.get(path).expiresAt=0;assert.equal((await callback(binding)).statusCode,400);docs.get(path).expiresAt=Date.now()+10000;
 assert.equal((await callback(binding)).statusCode,200);assert.equal((await callback(binding)).statusCode,400);assert.equal(calls,1);
 const stored=docs.get('linkedinConnections/'+hash('workspace:production'));assert.ok(stored.token.ciphertext);assert.ok(!JSON.stringify(stored).includes('private-access-token'));const status=await app.inject({url:base});assert.ok(!status.body.includes('ciphertext'));assert.ok(!status.body.includes('private-access-token'));
 await app.inject({method:'POST',url:base+'/disconnect'});assert.equal(docs.has('linkedinConnections/'+hash('workspace:production')),false);
 }finally{globalThis.fetch=old;await app.close();}
});
test('revoked role and declined consent cannot complete a connection',async()=>{const {app,authority}=setup();let r=await app.inject({method:'POST',url:base+'/start',payload:{binding}});let state=new URL(r.json().authorizationUrl).searchParams.get('state');r=await app.inject({method:'POST',url:base+'/callback',payload:{state,binding,error:'user_cancelled_authorize'}});assert.equal(r.statusCode,400);r=await app.inject({method:'POST',url:base+'/start',payload:{binding}});state=new URL(r.json().authorizationUrl).searchParams.get('state');authority.permissions.clear();r=await app.inject({method:'POST',url:base+'/callback',payload:{state,binding,code:'code'}});assert.equal(r.statusCode,403);await app.close();});
test('draft order is enforced, cross-workspace access denied and publishing always blocked',async()=>{const {app,docs}=setup();const r=await app.inject({method:'POST',url:base+'/drafts',payload:{text:'Approved only after preview'}});const url=base+'/drafts/'+r.json().id;assert.equal((await app.inject({method:'POST',url,payload:{action:'approve'}})).statusCode,409);assert.equal((await app.inject({method:'POST',url,payload:{action:'preview'}})).statusCode,200);assert.equal((await app.inject({method:'POST',url,payload:{action:'approve'}})).statusCode,200);assert.equal((await app.inject({method:'POST',url,payload:{action:'publish'}})).statusCode,409);docs.get('linkedinDrafts/'+r.json().id).workspaceId='other';assert.equal((await app.inject({method:'POST',url,payload:{action:'preview'}})).statusCode,403);assert.throws(()=>workflow('DRAFT','publish'));await app.close();});
test('provider failure is sanitised and consumed state cannot be retried',async()=>{const {app,docs}=setup();const old=fetch;globalThis.fetch=async()=>new Response('test-secret private-provider-details',{status:401});try{const r=await app.inject({method:'POST',url:base+'/start',payload:{binding}});const state=new URL(r.json().authorizationUrl).searchParams.get('state');const payload={state,binding,code:'private-code'};const failed=await app.inject({method:'POST',url:base+'/callback',payload});assert.equal(failed.statusCode,502);assert.ok(!failed.body.includes('test-secret')&&!failed.body.includes('private-provider-details'));assert.equal((await app.inject({method:'POST',url:base+'/callback',payload})).statusCode,400);assert.ok(![...docs.keys()].some(k=>k.startsWith('linkedinConnections/')));}finally{globalThis.fetch=old;await app.close();}});
test('workspace changes during consent are denied',async()=>{const {app,authority}=setup();const r=await app.inject({method:'POST',url:base+'/start',payload:{binding}});const state=new URL(r.json().authorizationUrl).searchParams.get('state');authority.workspaceId='different';assert.equal((await app.inject({method:'POST',url:base+'/callback',payload:{state,binding,code:'private-code'}})).statusCode,403);await app.close();});
