'use client';
import { useRef, useState } from 'react';
import PublicNav from '../../components/PublicNav';
import s from '../public.module.css';
export default function ConsultationPage() {
  const pending = useRef(false); const submission = useRef<{id:string;time:string}|null>(null);
  const [message,setMessage] = useState(''); const [busy,setBusy] = useState(false);
  return <main className={s.page}><div className={s.wrap}><PublicNav/><form aria-busy={busy} className={`${s.card} ${s.form}`} onSubmit={async e => { e.preventDefault(); if(pending.current)return; pending.current=true; setMessage(''); const form = e.currentTarget; const data = new FormData(form); const attempt=submission.current??{id:crypto.randomUUID(),time:new Date().toISOString()}; submission.current=attempt; setBusy(true); try { const response = await fetch('/api/consultations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(data),requestId:attempt.id,submittedAt:attempt.time})}); const body = await response.json(); setMessage(body.message); if(response.ok) {form.reset();submission.current=null;} } catch {setMessage('Connection lost. Please retry; your request ID is preserved.');} finally {pending.current=false;setBusy(false);} }}><p className={s.eyebrow}>Let’s talk about your market</p><h1>Book a consultation</h1><p>Tell us where you want better field visibility. We will contact you to arrange a suitable time.</p><label>Name<input disabled={busy} name="name" required maxLength={120} autoComplete="name"/></label><label>Work email<input disabled={busy} name="email" type="email" required maxLength={254} autoComplete="email"/></label><label>Company<input disabled={busy} name="company" required maxLength={160} autoComplete="organization"/></label><label>About your project<textarea disabled={busy} name="message" required minLength={10} maxLength={3000}/></label><div hidden><label>Website<input disabled={busy} name="website" tabIndex={-1} autoComplete="off"/></label></div><button className={s.button} disabled={busy}>{busy ? 'Sending…' : 'Request a consultation'}</button>{message && <p role="status">{message}</p>}<a href="mailto:consult@surveyguru.ai">Or email consult@surveyguru.ai directly →</a></form></div></main>;
}
